#!/bin/bash
echo Building...
./gradlew build -q

count=$1

function clean_up {
	if [[ count -eq 2 ]]; then
		kill -9 $pid1
		kill -9 $pid2
	else
                kill -9 $pid1
                kill -9 $pid2
		kill -9 $pid3
		kill -9 $pid4
	fi
}


if [[ count -eq 2 ]]; then
        echo Starting up two Servers
	xterm -e java -cp ./src main.java.server.EchoServer --port 7070 &
	pid1=$!
	xterm -e java -cp ./src main.java.server.EchoServer --port 7171 &
        pid2=$!

	echo Starting up viewer
	xterm -e java -cp ./src main.java.client.CMT localhost:7070 localhost:7171

	echo Happy Hacking~
else
        echo Starting up four Servers
        xterm -e java -cp ./src main.java.server.EchoServer --port 7070 &
        pid1=$!

        xterm -e java -cp ./src main.java.server.EchoServer --port 7171 &
        pid2=$!

        xterm -e java -cp ./src main.java.server.EchoServer --port 7272 &
        pid3=$!

        xterm -e java -cp ./src main.java.server.EchoServer --port 7373 &
        pid4=$!

        echo Starting up viewer
        xterm -e java -cp ./src main.java.client.CMT localhost:7070 localhost:7171 localhost:7272 localhost:7373 

	echo Happy Hacking~
fi

clean_up
exit 0
